### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by zfk513** [ROYL-Design/leanstorage-exporter#1]
请问为什么我无法成功从Ｄｅｍｏ导出文件，提示网络错误？谢谢

**Comment by NemoAlex** [comment]
是在导出文件的环节还是在查询的环节？

**Comment by zfk513** [comment]
emmm 就是demo里的connect就有问题……

**Comment by NemoAlex** [comment]
我检查了一下，没有哪里写着『网络错误』的提示。如果连接出错，应该会显示原因。

**Comment by zfk513** [comment]
![image](https://user-images.githubusercontent.com/29036702/41825539-00d04448-7854-11e8-8a95-8022a9d9d08f.png)

**Comment by NemoAlex** [comment]
https://api.leancloud.cn/1.1/stats/appinfo
访问这个，看看有没有 `{"code":401,"error":"Unauthorized."}`

**Comment by zfk513** [comment]
确实有……emm 可是我好像登陆了……
会不会是TAB（华东）的问题？

**Comment by NemoAlex** [comment]
说明连接没问题。会不会是 method=options 的 HTTP request 被你本地的防火墙拦截了？
需要你看一下 Chrome 的 console 才能知道。

**Comment by zfk513** [comment]
谢谢大大耐心的解释 不胜感激
Failed to load https://tab.leancloud.cn/1.1/appinfo?redirectByAPI=cn: Response for preflight has invalid HTTP status code 404.
console里面目前只看到了这个

**Comment by NemoAlex** [comment]
奇怪，为什么会跳转到 tab.leancloud.cn，我去社区问问

**Comment by zfk513** [comment]
好的，谢谢您
可能节点不一样，可能我没有充值氪金 orz

**Comment by NemoAlex** [comment]
https://forum.leancloud.cn/t/tab-leancloud-cn/18301

**Comment by leeyeh** [comment]
说明目标应用的 appid 是华东节点的。

**Comment by NemoAlex** [comment]
@leeyeh 这样的跳转是正常现象吗？华东节点需要专门使用别的 API 地址吗？

**Comment by leeyeh** [comment]
每个应用现在都有独立的域名，可以在这里获取：https://app-router.leancloud.cn/2/route?appId=rYAutyUJKH6i6DfUN0bqVx2x

https://api.leancloud.cn 是华北节点最早的域名为了兼容还可以使用，但也不推荐。

**Comment by NemoAlex** [comment]
@leeyeh 明白了，我改一下程序。
@zfk513 感谢汇报问题。

**Comment by NemoAlex** [comment]
@zfk513 我更新了，试一下吧

**Comment by zfk513** [comment]
🆗了，谢谢您
就是在问一下，列表显示的顺序捉摸不透，和我上传的顺序不一样，但是我这些数据其实是有排号，第一个值第二个值，感觉每次都要手动移好麻烦啊，请问有高招吗？

**Comment by NemoAlex** [comment]
@zfk513 暂时没有排序的功能。你可以在 Excel 里做排序。
